### ISSUE TITLE
OV2640 Low Power settings

### ISSUE THREAD

**Issue by steveww** [martinberlin/FS2#10]
From the sparse documentation I have found the following registers:

0x86 bit 2 borad LDO
0x86 bit 1 PWDN pin on sensor???
0x03 bit 6 low power mode control
0x05 bit 1, bit 2 sensor power down I/O
0x06 bit 1 sensor power down I/O
0x45 bit 1 sensor power down I/O

Alas this is all the documentation mentions. Please provide more information as to what these registers do and the impact of setting/clearing these bits.

My goal is to be able to put the board to sleep to reduce power consumption while running on batteries, waking up on demand.

**Comment by steveww** [comment]
Oops posted to the wrong repo.

**Comment by martinberlin** [comment]
No problem. I will be happy if you try to compile this project too :+1:
