### ISSUE TITLE
Streaming hangs up in ESP32 after 5 seconds

### ISSUE THREAD

**Issue by martinberlin** [martinberlin/FS2#3]
The function is called serverStream()

And it's in the original ArduCam demo. There must be something that makes the communication from the camera to stop or for some reason, the stream pipeline is broken.

Attempts to solve this:  I thought the problem was that the image resolution was too high, I tried lowering it down but is not the problem.
To reproduce it just press the Stream button in the **cam.local** web interface.

**Comment by martinberlin** [comment]
I know after some testing what was happening here. 
You cannot do a server.handleClient() in a loop while this is streaming a video.

So the solution was to make a counter and call it only one each 99 times:

```
int counter = 0;
while (true) {
   if (counter % 99 == 0) {
       server.handleClient();
   }
   counter++;
}
```

That seems to work, of course then stopping the streaming will have to wait, until it comes in the division of the number by 99 gives 0. But it's just a few seconds. 
If anyone has a better idea I'm happy to hear.

**Comment by tablatronix** [comment]
```C++
  response += "Content-Type: multipart/x-mixed-replace; boundary=frame\r\n\r\n";
  server.sendContent(response);
  server.close(); // <-- add this
```

the webserver thinks there is a new client the first time you run handle client, then it starts a 
#define HTTP_MAX_DATA_WAIT 5000 //ms to wait for the client to send the request
and waits for client to respond, since it doesnt m ,after 5 seconds it marks client as !keepCurrentClient and does a    ` _currentUpload.reset();`

So if we handle client manually in stream code, and close client before handleclient, it does not try to process it, since there is no new client. a flush might also work not sure.

**Comment by tablatronix** [comment]
ok one problem, if you disconnect you cannot reconnect, let me do a pr and fix that

**Comment by tablatronix** [comment]
this seems to work better
```C++
    // Use a handleClient only 1 every 99 times
    // if (counter % 99 == 0) {
       // Serial.println(client.status());
       if(!client.connected()) server.handleClient();
       // Serial.print(String(counter)+" % 99 Matched");
    // }
```

**Comment by tablatronix** [comment]
please reopen

This seems to be working

The only problem is you cannot navigate away from page unless you stop the page load ( it loads infinitely) this could be fixed by changing stream to a proper stream

**Comment by martinberlin** [comment]
Nice! Reopening, will test it tonight. Thanks for all the test, very interesting findings.

**Comment by martinberlin** [comment]
>The only problem is you cannot navigate away from page unless you stop the page load ( it loads infinitely) this might be fixed by changing stream to a proper stream

If you examplain how can I do something alike I will try it out. 
But yes the problem when you stream something is that making a server.handleClient() cuts the stream and without making it of course it does not respond to your intention to go away. It's a bit like what's first chicken or egg type of thing, that's why I though to make this call only 1 each 99 times, but it's also not the right approach. 
There must be a way to make a stream that can be interrupted somehow without cutting it making a server.handleClient() in the middle.

**Comment by tablatronix** [comment]
I will make a PR

**Comment by martinberlin** [comment]
Thanks Shawn. If you decide to put a battery to this thing in #9 I'm taking the steps to turn on the Camera only when needed. No idea if the NodeMCU board has something with a Mosfet like ESP32 VEXT but it's just a simple transistor anyway so it's not hard to install.  I will try again this tonight and report my outcome.

**Comment by martinberlin** [comment]
About this, I tested a bit more, and at the moment I don't find any other solution than to close the client to stop the stream (What is awkward)
An alternative is to detect an external event, like shooter boton press, to get out of the streaming loop. But to get out of the web UI and press a button is just a quick workaround. I'm testing all this in the ESP32 also and I wonder myself if it would be not possible to do the server.handleClient() with one of the CPUs and let the other one handle the SPI -> Arducam communication. That should work I think, then you can listen to client and serve the stream at the same time.

**Comment by martinberlin** [comment]
Yes I see. But could you manage to stream in another way ?

> this might be fixed by changing stream to a proper stream

What would be that ? Just tell me what you have in mind for "proper stream" I will make a demo.

**Comment by tablatronix** [comment]
I have no idea

**Comment by martinberlin** [comment]
Closing this till we find a better idea how to implement a better stream

**Comment by tablatronix** [comment]
Ill post my pr and look into it Inread you can send jpgs are an mpg stream

**Comment by martinberlin** [comment]
Thanks!  I will take a look then. I hope one day you will take more pictures, I still didn't met your cat ;)

**Comment by tablatronix** [comment]
I am waiting for battery from ebay
