### ISSUE TITLE
Add delay to all loops

### ISSUE THREAD

**Issue by tablatronix** [martinberlin/FS2#7]
Should add a delay(0) to end of every while, for loop ( there are a lot ) to avoid wdt resets if you are not servicing wifi in them already.

**Comment by martinberlin** [comment]
I will do it. It does not hang for me except in some critical loops but I agree that is a good practice to add them.

**Comment by martinberlin** [comment]
Fixed and code minimally refactored. I'll leave saveInSpiffs disabled to allow faster development, make sure to enable it if you want a backup of the photo on FS
https://github.com/martinberlin/FS2/compare/develop?expand=1

Thanks for the testing
