### ISSUE TITLE
use a button library that has library support, or include it

### ISSUE THREAD

**Issue by tablatronix** [martinberlin/FS2#8]
I had to manually install this button library as it is not in platformio , is it in arduinos?
Might be easier to write your own button listener or use a library that is more common.

**Comment by tablatronix** [comment]
suggestion oneButton lib

**Comment by martinberlin** [comment]
Very good suggestion will use this one. Sincerely speaking, is today the first time I hear about platformio-

**Comment by martinberlin** [comment]
Just installed Platform IO and Visual Studio Code. Looks very nice! So I will start using this instead of Arduino. Is possible also to upload ESP32 /ESP8266 /data folder to Spiffs with this tool ?

**Comment by martinberlin** [comment]
Done and merged in:
50bb226..5ecadbf  develop

If you find 3 minutes to upload the code just close it anytime later. Thanks for the platformio tip, great IDE!!!

**Comment by martinberlin** [comment]
oneButton up and running in ESP8266 version. I'm still debugging the ESP32 one, but IMHO ESP32 in this little project unless this double CPU is used for something is killing little birds with a canon ;) I like littlebirds and I dislike powder so I will keep the lower version more up-to-date
