### ISSUE TITLE
Take steps to get consumption down

### ISSUE THREAD

**Issue by martinberlin** [martinberlin/FS2#9]
This week is arriving a new Multimeter I got in amazon.de and my goal is to do a systematic analysis to get consumption down with this facts:

- Sketch (develop branch) without Arducam connected compiled for Wemos D1 is using 70mA. 
- Same sketch but with Arducam OV5642 connected is consuming about 170mA. That is way too much and unthinkable to work with a 2000mA battery. 

For that we need to measure this properly with both ESP8266 / ESP32 based boards and make some proper measurements about: 

- Consumption on setup()  (meaning WiFi setup / SPI Arducam connection and so on)
- Idle consumption (Doing nothing on the loop() )
- Consumption while sending a Photo through API upload ( I can imagine this is the consumption peak )

And then if you can give me a hand on this @tablatronix we can try to take some reasonable steps to make consumption go down without affecting usability. 
First 3 TOP actions here would be: 

1. Power the camera via a MOSFET or using VEXT if your board supports it, only power it in the second that you take the picture and then disconnect it the **hard way** 
2. Same with OLED display show anything for no more than 8/10 seconds, then make it off (Or sleep)
3. If you don't do any server.handleClient() action or you don't press the shooter the ESP32 will go into Deep sleep mode ( Not sure if it makes sense a sleepAfterMinutes new setting, for the moment no )

Current scenario with 2000mA battery is that the camera takes between 18/24 pictures and eats the battery out like a sweet donut. Let's see how far it will go with this updates.

Post research:

19.Nov.18 **Looking for a nice solution to switch the camera off on the "high side"**
https://forum.mysensors.org/topic/1991/turning-off-connected-arducam -> Here same request. At the recommends to use one of this transistors: https://www.fairchildsemi.com/datasheets/ND/NDP6020P.pdf
Maybe that's the way to go. The only detail is that turning the camera completely off will loose the configuration in setup()  so we will have to make a function that puts HIGH this transistor and also does the camera setup (Jpeg_size, flags, etc) before taking each photo.
Not only the camera should be turned of disconnecting the VCC pin, but also the SPI should be turned out, since will also draw some consumption through the data GPIOs (To be confirmed soon, if it's too little maybe I won't bother with this)
Some feedback around for my colleagues was that a 1 K resistor per data line of SPI will also work to reduce this consumption when the camera is in sleep mode.
@carlosfasani tells me that doing this may affect SPI speed (And it makes sense of course)
Saved for later: [ESP32 pinout reference](https://randomnerdtutorials.com/esp32-pinout-reference-gpios/)

ArduCam research: [Low-power](https://github.com/ArduCAM/Arduino/issues/136 )

**Comment by IoTPanic** [comment]
Hey @martinberlin,

What I would do is create a new ESP32 board with a PMIC that has two 3.3V rails one being a peripheral output such as Microchip MIC2230. One 3.3VDC rail would go to the ESP32 and would be enabled all the time, while when the camera is "sleeping" the ESP32 would disable the second output where the camera is connected. If you need SPI isolation (I don't think there is enough power draw through the GPIO to be concerned), could you use opto-isolaters with their power inputs connected to the same second 3.3V rail? This chip is a high efficiency switching DC-DC converter and you should get great battery life.

If you need help with a PCB lmk

**Comment by tablatronix** [comment]
That is what I was thinking also, if you want to go basic maybe some mosfets and a buffer ic.

**Comment by IoTPanic** [comment]
I apologize, I was waiting for a reply and my gmail marked this conversation as normal junk, you still want that PCB? If so, give me a list of features you'd like to see

**Comment by martinberlin** [comment]
Maybe it could work but as I commented before it's a too early stage to make something that will be quite fixed. If I would go for this, then I will simply do something like this: 
https://fasarek.de/FS2/schematics.php -> With an 8 output (2.54) pin SPI + IC2 cable that suits Arducam order like in this.
But for a ESP32 core, not esp8266, since it's faster and I would also like to explore more the possibility of using 2 CPU cores. 
Then we need a MOSFET like IRLML2246 that will be connected to one of the available Espressif GPIOS and will let 3.3v pass to the camera on LOW ( So this GPIO Low will let 3.3v to the camera VCC). And there is not too much more I think, except that we would need a battery connector, with a power circuit that allows charging a 3.7V LioN of at least 2000mA.
But most of all, I would like you to build one, I have some spare Arducam OV2640 and front/back cases. Send me an email to martin@luckycloud.de with your address and I will send you one. 
Because the only way to meet the requirements well and to experience what you need is to build one of this. And at the same time, you can evaluate if it makes sense or not. 
But anyways thanks for the initiative it sounds really cool and much more professional to have something like this. I just want to avoid you losing a lot of time on something previous testing it to the bone.

**Comment by martinberlin** [comment]
@IoTPanic I'm waiting for you to send me your address. It seems my email is still landing on the Junk box ;)
https://github.com/ArduCAM/Arduino/issues/380 -> After my intent to get a smarter way to make this camera wake up in a smart way after complete power off I must say the answer of Arducam mother company, UCTRONICS put me a bit down. There is no smart way to wait for a signal but an ugly way using delays that is highly error prone (And also changes from camera to camera) so I must say there is not too many ways to keep putting consumption down. And also this Issue is starting to make little sense. 
Since camera consumes up to 250mAh. Plus WiFi that takes another 100/140mAh then you have about 300+ mA per hour. That's insane ;)

**Comment by IoTPanic** [comment]
[FS2-sch.pdf](https://github.com/martinberlin/FS2/files/2659872/FS2-sch.pdf)

I will be honest, I went a little overboard, but I just had so much GPIO and yeah. If you want I will change out the screen connector to work with the screen I'm using or any other changes. Let me know any thoughts.

**Comment by martinberlin** [comment]
Thanks Samuel, looks very good. Also is good to have also cursor buttons so optionally is possible to add some simple menu. 
And from this KiCad is also possible to render the PCB ? 
Send it to my father @carlosfasani so he can check it up, he knows much more about electronics than me ;)

**Comment by IoTPanic** [comment]
Answers:

1. Yes, after I associate footprints with each part, then I can lay out and route the board, which then we can get 10 for $2 at jlcpcb.com
2. I made the board with the WROOM in mind, and my antenna wouldn't really have an advantage to the one on the module. If we were using the ESP32 chip, that could be a different story.
3. I added a Molex connector that is standard on most small single cell lithium-ion batteries such as the ones sold on websites like Adafruit. To change the battery, simply disconnect. I can add a battery charger if you want to utilize the USB port a little more.

Let me know what @carlosfasani thinks and after you and him are happy with it I will upload the KiCAD files for all to enjoy.

**Comment by tablatronix** [comment]
So the arducam docs say there is 2 power downs a bit to toggle the ldo enable off, requires cam init since settings are lost

And a bit to enter cam standby which preserves settings. 

Another thought if you are not making a pcb for a module add some kind of cheap vibration sensor so you can pre wake before pressing button or a light power up maybe..

**Comment by martinberlin** [comment]
Yeah but if my measurements are correct, at least the 5MP cam still consumes like 150 mA on low power mode that plus the WiFi running still eats your battery like a donut :). But I will try it again.
By the way I find arducam documentation and examples quite scarce
